create database DB_Trabalho;


--SEXO = {CODSEXO, NOMESEXO}
CREATE TABLE SEXO(
    COD_SEXO integer identity(1,1) PRIMARY KEY,
    NOME_SEXO VARCHAR(9) NOT NULL UNIQUE 
);

--RUA = {CODRUA, NOMERUA}
CREATE TABLE RUA(
    COD_RUA integer identity(1,1) PRIMARY KEY,
    NOME_RUA VARCHAR(80) NOT NULL UNIQUE
);

--BAIRRO = {CODBAIRRO, NOMEBAIRRO}
CREATE TABLE BAIRRO(
    COD_BAIRRO integer identity(1,1) PRIMARY KEY,
    NOME_BAIRRO VARCHAR(80) NOT NULL UNIQUE
);

--CEP = {CODCEP, NUMEROCEP}
CREATE TABLE CEP(
    COD_CEP integer identity(1,1) PRIMARY KEY,
    NUMERO_CEP CHAR(9) NOT NULL UNIQUE
);

--UF = {COD_UF, NOME_UF, SIGLA}
CREATE TABLE UF(
    COD_UF integer identity(1,1) PRIMARY KEY,
    NOME_UF VARCHAR(80) NOT NULL UNIQUE,
    SIGLA CHAR(2) NOT NULL UNIQUE
);

--CIDADE = {COD_CIDADE, NOME_CIDADE, COD_UF_FK}
CREATE TABLE CIDADE(
    COD_CIDADE integer identity(1,1) PRIMARY KEY,
    NOME_CIDADE VARCHAR(80) NOT NULL UNIQUE,

    COD_UF_FK integer REFERENCES UF(COD_UF)

);

--TRABALHO = {COD_TRABALHO, NOME_TRABALHO}
CREATE TABLE TRABALHO(
    COD_TRABALHO integer identity(1,1) PRIMARY KEY,
    NOME_TRABALHO VARCHAR(80) NOT NULL UNIQUE
);

--OPERADORA = {CODPERADORA, NOMEOPERADORA}
Create table OPERADORA(
COD_OPERADORA integer identity(1,1) PRIMARY KEY,
NOME_OPERADORA VARCHAR(80) NOT NULL UNIQUE
);
--TELEFONE = {COD_TELEFONE, NUMERO, COD_OPERADORA_FK}
CREATE TABLE TELEFONE(
    COD_TELEFONE integer identity(1,1) PRIMARY KEY,
    NUMERO VARCHAR(15) NOT NULL UNIQUE,

    COD_OPERADORA_FK INTEGER REFERENCES OPERADORA(COD_OPERADORA)
    
);

----------------------------------------------------------------
--CLIENTE = {COD_CLIENTE, NOME_CLIENTE, FOTO_CLIENTE,
--           DATANASC_CLIENTE , COD_SEXO_FK, COD_RUA_FK,
--           COD_BAIRRO_FK, COD_CEP_FK, COD_CIDADE_FK,
--           COD_TRABALHO_FK, SALARIO_CLIENTE, NUMEROCASA}
CREATE TABLE CLIENTE(
    COD_CLIENTE integer identity(1,1) PRIMARY KEY,
    NOME_CLIENTE VARCHAR(80) NOT NULL,
    FOTO_CLIENTE Varbinary(max),
    DATANASC_CLIENTE DATE,

    COD_SEXO_FK INTEGER REFERENCES SEXO(COD_SEXO)
    ,
    COD_RUA_FK INTEGER REFERENCES RUA(COD_RUA)
    ,
    COD_BAIRRO_FK INTEGER REFERENCES BAIRRO(COD_BAIRRO)
    ,
    COD_CEP_FK INTEGER REFERENCES CEP(COD_CEP)
    ,
    COD_CIDADE_FK INTEGER REFERENCES CIDADE(COD_CIDADE)
    ,
    COD_TRABALHO_FK INTEGER REFERENCES TRABALHO(COD_TRABALHO)
    ,

    SALARIO_CLIENTE NUMERIC(10,2) NOT NULL,
    NUMEROCASA VARCHAR(16) NOT NULL
);
select * from cliente;

--ITENS_TEL_CLI = {COD_TELEFONE_FK, COD_CLIENTE_FK}
CREATE TABLE ITENS_TEL_CLI(
COD_TELEFONE_FK INTEGER REFERENCES TELEFONE(COD_TELEFONE)
,
COD_CLIENTE_FK INTEGER REFERENCES CLIENTE(COD_CLIENTE)
,

PRIMARY KEY( COD_TELEFONE_FK, COD_CLIENTE_FK)
);

--ITENS_TEL_TRA = {COD_TRABALHO_FK, COD_TELEFONE_FK}
CREATE TABLE ITENS_TEL_TRA(
COD_TRABALHO_FK INTEGER REFERENCES TRABALHO(COD_TRABALHO)
,
COD_TELEFONE_FK INTEGER REFERENCES TELEFONE(COD_TELEFONE)
,

PRIMARY KEY(COD_TRABALHO_FK, COD_TELEFONE_FK)
);

--FUNCAO = {COD_FUNCAO, NOME_FUNCAO}
CREATE TABLE FUNCAO(
    COD_FUNCAO integer identity(1,1) PRIMARY KEY,
    NOME_FUNCAO VARCHAR(80) NOT NULL UNIQUE
);

--LOJA = {COD_LOJA, NOME_LOJA, CNPJ, NOME_FANTASIA, RAZAOSOCIAL}
CREATE TABLE LOJA(
    COD_LOJA integer identity(1,1) PRIMARY KEY,
    NOME_LOJA VARCHAR(80) NOT NULL UNIQUE,
    CNPJ VARCHAR(80) NOT NULL UNIQUE,
    NOME_FANTASIA VARCHAR(80) NOT NULL UNIQUE,
    RAZAOSOCIAL VARCHAR(80) NOT NULL UNIQUE
);

--FUNCIONARIOS = {COD_FUNCIONARIO, NOME_FUNCIONARIO, NUMEROCASA,
--COD_RUA_FK, COD_BAIRRO_FK, COD_CEP_FK, COD_CIDADE_FK, COD_FUNCAO_FK,
-- SALARIO, COD_LOJA_FK}
CREATE TABLE FUNCIONARIOS(
    COD_FUNCIONARIO integer identity(1,1) PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(80) NOT NULL,
    NUMEROCASA VARCHAR(9) NOT NULL,

    COD_RUA_FK INTEGER REFERENCES RUA(COD_RUA)
    ,
    COD_BAIRRO_FK INTEGER REFERENCES BAIRRO(COD_BAIRRO)
    ,
    COD_CEP_FK INTEGER REFERENCES CEP(COD_CEP)
    ,
    COD_CIDADE_FK INTEGER REFERENCES CIDADE(COD_CIDADE)
    ,
    COD_FUNCAO_FK INTEGER REFERENCES FUNCAO(COD_FUNCAO)
    ,
    COD_LOJA_FK INTEGER REFERENCES LOJA(COD_LOJA)
    ,

    SALARIO NUMERIC(10,2) NOT NULL
);

-- ITENS_TEL_FUN = {COD_FUNCIONARIO_FK, COD_TELEFONE_FK}
CREATE TABLE ITENS_TEL_FUN(
    COD_FUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(COD_FUNCIONARIO)
    ,
    COD_TELEFONE_FK INTEGER REFERENCES TELEFONE(COD_TELEFONE)
    ,

    PRIMARY KEY(COD_FUNCIONARIO_FK, COD_TELEFONE_FK)
);

--LOGINS = {COD_LOGINS, USUARIO, SENHA, COD_FUNCIONARIO_FK}
CREATE TABLE LOGINS(
    COD_LOGINS integer identity(1,1) PRIMARY KEY,
    USUARIO VARCHAR(80) NOT NULL UNIQUE,
    SENHA VARCHAR(80) NOT NULL UNIQUE,

    COD_FUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(COD_FUNCIONARIO)
    
);

-- CONTROLE_LOGSISTEMA = {COD_CONTROLE, COD_LOGINS_FK, DATA, HORA}
CREATE TABLE CONTROLE_LOGSISTEMA(
    COD_CONTROLE integer identity(1,1) PRIMARY KEY,
    
    COD_LOGINS_FK INTEGER REFERENCES LOGINS(COD_LOGINS)
    ,

    DATAS DATE NOT NULL,
    HORA TIME NOT NULL
);

--ACESSO = {COD_ACESSO, NOME_ACESSO}
CREATE TABLE ACESSO(
    COD_ACESSO integer identity(1,1) PRIMARY KEY,
    NOME_ACESSO VARCHAR(80) NOT NULL UNIQUE
);

--ITENS_ACESSOLOGIN = {COD_ACESSO_FK, COD_LOGINS_FK}
CREATE TABLE ITENS_ACESSOLOGIN(
    COD_ACESSO_FK INTEGER REFERENCES ACESSO(COD_ACESSO)
    ,
    COD_LOGINS_FK INTEGER REFERENCES LOGINS(COD_LOGINS)
    ,

    PRIMARY KEY(COD_ACESSO_FK, COD_LOGINS_FK)
);

--ITENS_TEL_LOJA={COD_LOJA_FK, COD_TELEFONE_FK}
CREATE TABLE ITENS_TEL_LOJA(
    COD_LOJA_FK INTEGER REFERENCES LOJA(COD_LOJA)
    ,
    COD_TELEFONE_FK INTEGER REFERENCES TELEFONE(COD_TELEFONE)
    ,

    PRIMARY KEY(COD_LOJA_FK, COD_TELEFONE_FK)
);

-- MARCA={COD_MARCA, NOME_MARCA}
CREATE TABLE MARCA(
    COD_MARCA integer identity(1,1) PRIMARY KEY,
    NOME_MARCA VARCHAR(80) NOT NULL UNIQUE
);

-- TIPO={COD_TIPO, NOME_TIPO}
CREATE TABLE TIPO(
    COD_TIPO integer identity(1,1) PRIMARY KEY,
    NOME_TIPO VARCHAR(80) NOT NULL UNIQUE
);

--PRODUTO = {COD_PRODUTO, NOME_PRODUTO, QUANTIDADE, 
--VALOR, COD_MARCA_FK, COD_TIPO_FK}
CREATE TABLE PRODUTO(
    COD_PRODUTO integer identity(1,1) PRIMARY KEY,
    NOME_PRODUTO VARCHAR(80) NOT NULL,
    QUANTIDADE NUMERIC(10) NOT NULL,
    VALOR NUMERIC(10, 2) NOT NULL,
    
    COD_MARCA_FK INTEGER REFERENCES MARCA(COD_MARCA)
    , 
    COD_TIPO_FK INTEGER REFERENCES TIPO(COD_TIPO)
    
);

--FORNECEDOR={COD_FORNECEDOR, NOME_FORNECEDOR, NUMEROCASA, COD_RUA_FK, 
--COD_BAIRRO_FK, COD_CEP_FK, COD_CIDADE_FK}
CREATE TABLE FORNECEDOR(
    COD_FORNECEDOR integer identity(1,1) PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(80) NOT NULL UNIQUE,
    NUMEROCASA VARCHAR(9) NOT NULL,

    COD_RUA_FK INTEGER REFERENCES RUA(COD_RUA)
    ,
    COD_BAIRRO_FK INTEGER REFERENCES BAIRRO(COD_BAIRRO)
    ,
    COD_CEP_FK INTEGER REFERENCES CEP(COD_CEP)
    ,
    COD_CIDADE_FK INTEGER REFERENCES CIDADE(COD_CIDADE)
    
);

--ITENS_TEL_FOR={COD_TELEFONE_FK, COD_FORNECEDOR_FK}
CREATE TABLE ITENS_TEL_FOR(
    COD_TELEFONE_FK INTEGER REFERENCES TELEFONE(COD_TELEFONE)
    ,
    COD_FORNECEDOR_FK INTEGER REFERENCES FORNECEDOR(COD_FORNECEDOR)
    ,

    PRIMARY KEY(COD_TELEFONE_FK, COD_FORNECEDOR_FK)
);

--COMPRAPRODUTO = {COD_COMPRA, DATA_COMPRA, COD_FORNECEDOR_FK, 
--COD_FUNCIONARIO_FK}
CREATE TABLE COMPRAPRODUTO(
    COD_COMPRA integer identity(1,1) PRIMARY KEY,
    DATA_COMPRA DATE NOT NULL,
    
    COD_FORNECEDOR_FK INTEGER REFERENCES FORNECEDOR(COD_FORNECEDOR)
    ,
    COD_FUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(COD_FUNCIONARIO)
    
);

--ITENS_COMPRA_PRODUTO = {COD_COMPRA_FK, COD_PRODUTO_FK, QUANTIDADE, VALORC}
CREATE TABLE ITENS_COMPRA_PRODUTO(
    COD_COMPRA_FK INTEGER REFERENCES COMPRAPRODUTO(COD_COMPRA)
    ,
    COD_PRODUTO_FK INTEGER REFERENCES PRODUTO(COD_PRODUTO)
    ,

    QUANTIDADE NUMERIC(12) NOT NULL,
    VALOC NUMERIC(10,2) NOT NULL,

    PRIMARY KEY (COD_COMPRA_FK, COD_PRODUTO_FK)
);

--SITUACAO = (COD_SITUACAO, NOME_SITUACAO)
CREATE TABLE SITUACAO(
    COD_SITUACAO integer identity(1,1) PRIMARY KEY,
    NOME_SITUACAO VARCHAR(80) NOT NULL UNIQUE
);

--PARCELACOMPRA = {COD_PARCELACOMPRA, DATA_VENCIMENTO, VALOR, 
--COD_SITUACAO, COD_COMPRA}
CREATE TABLE PARCELACOMPRA(
    COD_PARCELACOMPRA integer identity(1,1) PRIMARY KEY,
    DATA_VENCIMENTO DATE NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,

    COD_SITUACAO_FK INTEGER REFERENCES SITUACAO(COD_SITUACAO)
    ,
    COD_COMPRA_FK INTEGER REFERENCES COMPRAPRODUTO(COD_COMPRA)
    
);

-- VENDAPRODUTO = {COD_VENDA, DATAVENDA, COD_CLIENTE_FK, COD_FUNCIONARIO_FK}
CREATE TABLE VENDAPRODUTO(
    COD_VENDA integer identity(1,1) PRIMARY KEY,
    DATAVENDA DATE NOT NULL,

    COD_CLIENTE_FK INTEGER REFERENCES CLIENTE(COD_CLIENTE) 
    ,
    COD_FUNCIONARIO_FK INTEGER REFERENCES FUNCIONARIOS(COD_FUNCIONARIO)
     
);

-- ITENS_VENDAPRODUTO = {COD_VENDA_FK,COD_PRODUTO_FK, QUANTIDADE, VALOR}
CREATE TABLE ITENS_VENDAPRODUTO(
    COD_VENDA_FK INTEGER REFERENCES VENDAPRODUTO(COD_VENDA)
    ,
    COD_PRODUTO_FK INTEGER REFERENCES PRODUTO(COD_PRODUTO)
    ,

    QUANTIDADE NUMERIC(12) NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,

    PRIMARY KEY (COD_VENDA_FK, COD_PRODUTO_FK)
);

-- PARCELAVENDA={COD_PARCELA, DATA_VENCIMENTO, VALOR, COD_SITUACAO_FK, COD_VENDA_FK}
CREATE TABLE PARCELAVENDA(
    COD_PARCELA integer identity(1,1) PRIMARY KEY,
    DATA_VENCIMENTO DATE NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,

    COD_SITUACAO_FK INTEGER REFERENCES SITUACAO(COD_SITUACAO)
    ,
    COD_VENDA_FK INTEGER REFERENCES VENDAPRODUTO(COD_VENDA)
    
);

--  IMAGENS={COD_IMAGENS, IMAGEM, DESCRICAO, COD_PRODUTO_FK}
CREATE TABLE IMAGENS(
    COD_IMAGENS integer identity(1,1) PRIMARY KEY,
    IMAGEM Varbinary(max),
    DESCRICAO VARCHAR(200),

    COD_PRODUTO_FK INTEGER REFERENCES PRODUTO(COD_PRODUTO)
    
);